credentials:
  usernames:
    arpit:
      email: your-email@example.com
      name: Arpit
      city: Chandigarh
      area: Sector 1
      role: Admin
      password: '$2b$12$2fSV/bY/N4B7uzhF4q8M7OUiFXgcidyXfspluEoOpDZRfmE3ZIZei'
cookie:
  expiry_days: 1
  key: a8f3d2e1b9c7f4a0e5d6c3b2a1f8e7d4c9b0a3f2e1d8c7b6a5f4e3d2c1b0a9
  name: random_cookie_name
preauthorized:
  emails:
  - your-email@example.com
